#################################################
# DO Community Playbooks: Docker
#################################################
---
- hosts: localhost
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest


    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Start and Enable docker service
      shell: systemctl enable docker; systemctl start docker
      args:
        executable:  /bin/bash
      register: docker_enable
      become: true

    - name: check docker service status
      shell:  systemctl status docker
      args:
        executable: /bin/bash
      register: docker_status
      become: true
      until: "'active' and 'running' in docker_status.stdout"
      delay: 30
      retries: 5


    - name: Download minikube packages
      shell: curl {{ item }}
      args:
        executable:  /bin/bash
      become: true
      with_items: "{{ curl_packages }}"

    - name: Change file permissions
      shell: chmod +x minikube kubectl
      become: true

    - name: Move to the bin folder
      shell:  mv kubectl minikube /usr/local/bin/
      become: true

    - name: Setup the directory for storing Minikube and kubectl configuration.
      shell: mkdir $HOME/.kube || true
      become: true

    - name: Create empty file(config) under directory.
      shell: touch $HOME/.kube/config
      become: true


    - name: delete Minikube 
      shell: minikube delete
      become: true

    - name: copy these configuration  line
      shell: |
        echo 'export MINIKUBE_WANTUPDATENOTIFICATION=false' >> ~/.profile,
        echo 'export MINIKUBE_WANTREPORTERRORPROMPT=false' >> ~/.profile
        echo 'export MINIKUBE_HOME=$HOME' >> ~/.profile
        echo 'export CHANGE_MINIKUBE_NONE_USER=true' >> ~/.profile
        echo 'export KUBECONFIG=$HOME/.kube/config' >> ~/.profile
      become: true

    - name: Start Minikube with option vm-driver=none
      shell: minikube start --vm-driver=none
      args:
        executable: /bin/bash
      become: true

    - name: After minikube configuration, we check minikube status
      shell: minikube status
      args:
        executable: /bin/bash
      register: minikube_status
      become: true
      until: "'minikube' and 'Running' in minikube_status.stdout"
      delay: 30
      retries: 10

    - name: wait untill master  is ready 
      shell: kubectl get nodes
      args:
        executable: /bin/bash
      register: master_status
      become: true
      until: "'master' and 'Ready' in master_status.stdout"
      delay: 30
      retries: 10

    - name: STATUS
      shell: kubectl get nodes
      args:
        executable: /bin/bash
      become: true

    - name: Install openshift 
      pip:
        name: openshift
      become: true

    - name: Create a k8s namespace
      k8s:
        name: testing
        api_version: v1
        kind: Namespace
        state: present
      become: true
    
    - name: create dir
      become: true
      shell: "mkdir -p $HOME/kubeflow"

    - name: moving to dir kuberflow
      become: true
      shell: "cd $HOME/kubeflow"

    - name: download kfctl_v1.0-0-g94c35cf_linux.tar.gz
      become: true
      shell: "wget https://github.com/kubeflow/kfctl/releases/download/v1.0/kfctl_v1.0-0-g94c35cf_linux.tar.gz"

    - name: download kfctl_k8s_istio.v1.0.2.yaml
      become: true
      shell: "wget https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.2.yaml"

    - name: untar kfctl_v1.0-0-g94c35cf_linux.tar.gz
      args:
        executable: /bin/bash
      become: true
      shell: "tar -xvf kfctl_v1.0-0-g94c35cf_linux.tar.gz"

    - name: Change kfctl permissions
      shell: chmod +x kfctl
      become: true


    - name : print path
      become: true
      shell:  echo $PATH 


    - name: running kfctl
      become: true
      shell: ./kfctl apply -V -f kfctl_k8s_istio.v1.0.2.yaml

    - name: get kuberflow pods
      become: true
      name: "kubeflow Status"
      register: output
      delay: 5000
      shell: "kubectl get all -n kubeflow"




